### ISSUE TITLE
Cookie path is not read from web.xml

### ISSUE THREAD

**Issue by nbogojevic** [AmadeusITGroup/HttpSessionReplacer#23]
Cookie path if specified in web.xml is not taken into account.

```
<session-config>
    <cookie-config>
        <path>/somepath</path>
    </cookie-config>
</session-config>
```

The fix should be probably include adaptation in CookieSessionTracking and WebXmlParser#lookForSessionConf

**Comment by bferrenq** [comment]
PR ongoing:
https://github.com/AmadeusITGroup/HttpSessionReplacer/pull/24
Before approval, to be analyzed why WebXmlParser is invoked twice from 2 different threads...

**Comment by mederel** [comment]
Seems the PR is merged, the issue can be closed?
