### ISSUE TITLE
Question - Is there is a way to provide Redis password?

### ISSUE THREAD

**Issue by dinbtechit** [AmadeusITGroup/HttpSessionReplacer#53]
First of all want to appreciate your great work! hats off!

Question... We are using a cloud-based Redis instance, is there a way to supply a password?

**Comment by dinbtechit** [comment]
I had to make some code changes to pass in the `password ` and enable `SSL`. If you are accessing the Redis instance in Azure or AWS it requires password and obviously you will need SSL enabled as well. 

**Modified following changes:**
# RedisConfiguration.java
# JedisSessionRepositoryFactory.java

I would more than happy to make that change for you. But let me know if you want me to submit a PR for this.

**Comment by nbogojevic** [comment]
Hi @dinbtechit,

Yes, please do submit a PR. It's great idea.

Nenad

**Comment by dinbtechit** [comment]
Submitted Pull request. https://github.com/AmadeusITGroup/HttpSessionReplacer/pull/54
